#!/usr/bin/env python3
"""Bundle the UI in app/ into one self-contained file: dist/cloinear.html.

Drop that file next to (or inside) any ticket folder, open it in a Chromium
browser, pick the folder once, and the board reads and writes the .md files
directly. No server, no install. Browsers block <script src> modules and
fetch() on file:// pages, so all CSS and JS are inlined.

Zero dependencies: python3 standard library only.

    python3 bundle.py            # write dist/cloinear.html
    python3 bundle.py --check    # exit 1 if dist/cloinear.html is missing or stale

Modules are wrapped in their own function scope, so two modules may define the
same private helper. Only the import/export forms used in app/ are supported:
    import { a, b } from "./x.js";
    export function f() {} / export async function f() {} / export class C {} / export const x = ...
"""

import base64
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.join(ROOT, "app")
OUT_PATH = os.path.join(ROOT, "dist", "cloinear.html")

IMPORT_RE = re.compile(r'^import\s*\{([^}]*)\}\s*from\s*"([^"]+)";?\s*$', re.M)
EXPORT_RE = re.compile(r"^export\s+(?:async\s+)?(?:function\*?|class|const|let)\s+([A-Za-z_$][\w$]*)", re.M)


def module_var(path):
    rel = os.path.relpath(path, APP_DIR)
    return "__mod_" + re.sub(r"\W", "_", os.path.splitext(rel)[0])


def bundle_js(entry):
    """Return the JS for `entry` and its imports, dependencies first."""
    order, seen = [], set()

    def visit(path):
        if path in seen:
            return
        seen.add(path)
        with open(path, "r", encoding="utf-8") as fh:
            src = fh.read()
        for _names, spec in IMPORT_RE.findall(src):
            visit(os.path.normpath(os.path.join(os.path.dirname(path), spec)))
        order.append((path, src))

    visit(entry)

    chunks = []
    for path, src in order:
        exports = EXPORT_RE.findall(src)

        def rewrite_import(m, path=path):
            names = ", ".join(n.strip() for n in m.group(1).split(",") if n.strip())
            dep = os.path.normpath(os.path.join(os.path.dirname(path), m.group(2)))
            return f"const {{ {names} }} = {module_var(dep)};"

        body = IMPORT_RE.sub(rewrite_import, src)
        body = re.sub(r"^export\s+", "", body, flags=re.M)
        rel = os.path.relpath(path, ROOT)
        if path == entry:
            chunks.append(f"// ---- {rel} ----\n{{\n{body}\n}}")
        else:
            chunks.append(
                f"// ---- {rel} ----\nconst {module_var(path)} = (() => {{\n{body}\n"
                f"return {{ {', '.join(exports)} }};\n}})();"
            )
    return "\n\n".join(chunks)


def pin_script_hashes(html):
    """Allow only the exact inline scripts of the bundle in the CSP."""
    csp_src = "script-src 'self' 'unsafe-inline'"
    if csp_src not in html:
        raise SystemExit(f"bundle.py: expected `{csp_src}` in the CSP of app/index.html")
    hashes = [
        "'sha256-" + base64.b64encode(hashlib.sha256(body.encode("utf-8")).digest()).decode() + "'"
        for body in re.findall(r"<script[^>]*>(.*?)</script>", html, re.S)
    ]
    return html.replace(csp_src, "script-src " + " ".join(hashes), 1)


def build():
    with open(os.path.join(APP_DIR, "index.html"), "r", encoding="utf-8") as fh:
        html = fh.read()
    with open(os.path.join(APP_DIR, "styles.css"), "r", encoding="utf-8") as fh:
        css = fh.read()
    js = bundle_js(os.path.join(APP_DIR, "app.js"))

    css_tag = '<link rel="stylesheet" href="styles.css" />'
    js_tag = '<script type="module" src="app.js"></script>'
    for tag in (css_tag, js_tag):
        if tag not in html:
            raise SystemExit(f"bundle.py: expected `{tag}` in app/index.html")
    # Guard against the inlined code closing its own tag early.
    if "</script" in js.lower() or "</style" in css.lower():
        raise SystemExit("bundle.py: inlined code contains a closing </script> or </style> tag")

    html = html.replace(css_tag, f"<style>\n{css}</style>")
    html = html.replace(js_tag, f'<script type="module">\n{js}\n</script>')
    html = pin_script_hashes(html)
    header = "<!-- Generated by bundle.py from app/. Edit app/, not this file. -->\n"
    return header + html


def main(argv):
    payload = build()
    if "--check" in argv:
        current = None
        if os.path.isfile(OUT_PATH):
            with open(OUT_PATH, "r", encoding="utf-8") as fh:
                current = fh.read()
        if current != payload:
            print("dist/cloinear.html is missing or stale; run: python3 bundle.py", file=sys.stderr)
            return 1
        print("dist/cloinear.html is up to date.")
        return 0

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(payload)
    print(f"Wrote dist/cloinear.html ({len(payload) // 1024} KB).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
